View Resolution 번역 추가
homelus/spring-mvc-study pull request #14
Opened 2019-10-21 14:10 UTC by sefide

View Resolution 번역본 추가합니다.
resolve라는 동사가 많이 사용되는데 해석을 어떻게 해야할지 고민돼요.
혹시 좋은 표현이 있을까요 ?

2019-10-21 15:27 UTC, pplenty commented
"해석하다" 가 제일 자연스럽지 않을까요?
뷰 해석기
매개변수 해석기

2019-10-21 15:30 UTC, pplenty requested changes

2019-10-21 15:30 UTC, pplenty commented on documents/spring-framework-reference/ko/DispatcherServlet/1.1.8. View Resolution.md
> +#### [1.1.8. View Resolution](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-servlet-special-bean-types)
link 주소가 바껴야할 것 같아요

2019-10-27 02:25 UTC, sefide commented on documents/spring-framework-reference/ko/DispatcherServlet/1.1.8. View Resolution.md
> +#### [1.1.8. View Resolution](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-servlet-special-bean-types)
감사합니다 :) 수정했어요 !

2019-10-27 11:27 UTC, homelus reviewed
고생했어요 !
어려웠을 텐데 잘 작성했네요 💯 👍 
코멘트 조금 남겼어요 : )

2019-10-27 11:27 UTC, homelus commented on documents/spring-framework-reference/ko/DispatcherServlet/1.1.8. View Resolution.md
> +뷰 리졸버의 계약에서는 뷰를 찾을 수 없음을 나타내기 위해 null을 반환할 수 있도록 합니다. JSP와 InternalResourceViewResolver의 경우, JSP 존재 여부를 확인하는 유일한 방법은 RequestDispatcher를 이용해 dispatch를 동작시켜보는 것입니다. 따라서 당신은 InternalResourceViewResolver
계약이라는 의미는 생략해도 괜찮을 거 같아요 : )
InternalResourceViewResolver 를 마지막에 위치시키는 이유를 알고 넘어가면 좋을 거 같은데 저도 찾아보는데 명확히 느껴지지 않네요

When chaining ViewResolvers, an InternalResourceViewResolver
always needs to be last, as it will attempt to resolve any view name,
no matter whether the underlying resource actually exists.

2019-10-27 11:27 UTC, homelus commented on documents/spring-framework-reference/ko/DispatcherServlet/1.1.8. View Resolution.md
> +View Resolution을 설정하는 것은 스프링에서 뷰 리졸버를 빈으로 설정하는 것만큼 간단합니다.  [MVC Config]([https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-config](https://docs.spring.io/spring/docs/
무논리라기보다ㅎㅎ 
논리적인 처리가 없는 뷰 컨트롤러라고 하면 어떤가요
여기서 말하는 logic-less 는  단순 뷰를 보여주기 위한 컨트롤러를 말한느 것 같네요

2019-10-27 11:27 UTC, homelus commented on documents/spring-framework-reference/ko/DispatcherServlet/1.1.8. View Resolution.md
> +네트 효과는 마치 컨트롤러가 RedirectView를 반환하는 것 같지만 이제는 컨트롤러 자체가 논리적 뷰 이름으로 동작할 수 있습니다. 'redirect:/myapp/some/resource'와 같은 논리적 뷰 이름은 현재 서블릿 컨텍스트로  리다이렉트하고, 반면에 'redirect:https://myhost.com/some/arbitrary/path'
이제는/자체가 
구지(?) 필요없는 수식어는 빼버리면 좀 더 명료할 거 같아요 : )


relative 는 상대경로로 해석하면 어떨까요

2019-10-27 11:27 UTC, homelus commented on documents/spring-framework-reference/ko/DispatcherServlet/1.1.8. View Resolution.md
> +**Accept** 헤더는 'text/*' 과 같이 와일드카드를 포함할 수 있습니다. 이는 **Content-type**이 'text/xml'인 뷰는 호환이 되는 일치 항목입니다.
아마 아스타(별표) 를 쓰려면 이렇게 해야할 거에요

마크다운에서는 *, `, \와 같이 특별한 의미를 가진 마크업 문자 그 자체를 얻기 위해서 backslash(\)를 사용합니다. ‘\’를 얻고 싶으면 escaped backslash(\ \)를 사용합니다.

2019-11-05 13:51 UTC, sefide commented on documents/spring-framework-reference/ko/DispatcherServlet/1.1.8. View Resolution.md
> +View Resolution을 설정하는 것은 스프링에서 뷰 리졸버를 빈으로 설정하는 것만큼 간단합니다.  [MVC Config]([https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-config](https://docs.spring.io/spring/docs/
앟ㅎ 맞아요. 문장이 너무 길어지는 것 같아 고민되었는데 아무래도 문장이 길어지더라도 확실하게 표현하는게 좋을 것 같아요 !

2019-11-05 14:22 UTC, sefide commented on documents/spring-framework-reference/ko/DispatcherServlet/1.1.8. View Resolution.md
> +**Accept** 헤더는 'text/*' 과 같이 와일드카드를 포함할 수 있습니다. 이는 **Content-type**이 'text/xml'인 뷰는 호환이 되는 일치 항목입니다.
앗 감사합니다 :) @homelus 님 혹시 별표(*)가 안보이시나요? backslash를 사용하지 않아도 깃헙 마크다운에서는 별표가 보이는 것 같아서요 !

2019-11-11 04:40 UTC, homelus commented
오 고생하셨어요ㅋㅋ 확인했습니다
머지하고 별표는 확인해볼게요  !

2019-11-11 04:40 UTC, merged